name: simod
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=21.4.0=pyhd8ed1ab_0
  - blas=2.113=openblas
  - blas-devel=3.9.0=13_osxarm64_openblas
  - bottleneck=1.3.4=py39heec5a64_0
  - brotli=1.0.9=h3422bc3_6
  - brotli-bin=1.0.9=h3422bc3_6
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2021.10.8=h4653dfc_0
  - certifi=2021.10.8=py39h2804cbe_2
  - cffi=1.15.0=py39h52b1de0_0
  - cfgv=3.3.1=pyhd8ed1ab_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - coverage=6.3.2=py39h1a28f6b_0
  - cvxopt=1.2.6=py39hc9edfa2_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - distlib=0.3.4=pyhd8ed1ab_0
  - dsdp=5.8=hc9edfa2_0
  - fftw=3.3.9=h1a28f6b_1
  - filelock=3.6.0=pyhd8ed1ab_0
  - freetype=2.11.0=h1192e45_0
  - future=0.18.2=py39h2804cbe_3
  - giflib=5.2.1=h27ca646_2
  - glpk=4.65=h695f6f0_2
  - gmp=6.2.1=h9f76cd9_0
  - gsl=2.6=hc9edfa2_0
  - hyperopt=0.2.5=pyh9f0ad1d_0
  - icu=68.2=hbdafb3b_0
  - identify=2.4.12=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - jbig=2.1=h3422bc3_2003
  - jellyfish=0.9.0=py39h1a28f6b_0
  - jpeg=9e=h3422bc3_0
  - lcms2=2.12=had6a04f_0
  - lerc=2.2.1=h9f76cd9_0
  - libblas=3.9.0=13_osxarm64_openblas
  - libbrotlicommon=1.0.9=h3422bc3_6
  - libbrotlidec=1.0.9=h3422bc3_6
  - libbrotlienc=1.0.9=h3422bc3_6
  - libcblas=3.9.0=13_osxarm64_openblas
  - libcxx=12.0.0=hf6beb65_1
  - libdeflate=1.7=h27ca646_5
  - libffi=3.4.2=hc377ac9_2
  - libgfortran=5.0.0=11_1_0_h6a59814_26
  - libgfortran5=11.1.0=h6a59814_26
  - libiconv=1.16=h642e427_0
  - liblapack=3.9.0=13_osxarm64_openblas
  - liblapacke=3.9.0=13_osxarm64_openblas
  - libopenblas=0.3.18=openmp_h5dd58f0_0
  - libpng=1.6.37=hf7e6567_2
  - libtiff=4.3.0=hc6122e1_1
  - libwebp=1.2.2=h0d20362_0
  - libwebp-base=1.2.2=h3422bc3_1
  - libxml2=2.9.12=h538f51a_0
  - libxslt=1.1.34=h9833966_0
  - libzlib=1.2.11=h90dfc92_1014
  - llvm-openmp=13.0.1=h455960f_1
  - lxml=4.8.0=py39h2fae87d_0
  - lz4-c=1.9.3=hbdafb3b_1
  - matplotlib=3.5.1=py39hdf13c20_0
  - matplotlib-base=3.5.1=py39hc377ac9_1
  - metis=5.1.0=hc377ac9_0
  - mpfr=4.0.2=h695f6f0_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h1a28f6b_2
  - networkx=2.7.1=pyhd8ed1ab_0
  - nodeenv=1.6.0=pyhd8ed1ab_0
  - numexpr=2.8.1=py39h144ceef_0
  - numpy-base=1.21.2=py39h6269429_0
  - openblas=0.3.18=openmp_h3b88efd_0
  - openssl=3.0.2=h90dfc92_1
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - pluggy=1.0.0=py39h2804cbe_1
  - pre-commit=2.18.1=py39h2804cbe_1
  - py=1.11.0=pyh6c4a22f_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pymongo=3.12.0=py39hc377ac9_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pytest-cov=3.0.0=pyhd3eb1b0_0
  - python=3.9.12=h14b404e_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=pyhd8ed1ab_0
  - pyyaml=6.0=py39h5161555_0
  - readline=8.1.2=h1a28f6b_1
  - setuptools=58.0.4=py39hca03da5_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.2=h1058600_0
  - suitesparse=5.10.1=hee66609_0
  - tbb=2021.5.0=h525c30c_0
  - tk=8.6.12=he1e0b03_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.1=py39h5161555_1
  - tqdm=4.63.1=pyhd8ed1ab_0
  - tzdata=2022a=hda174b7_0
  - ukkonen=1.0.1=py39h4d2d688_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xmltodict=0.12.0=py_0
  - xz=5.2.5=h1a28f6b_0
  - yaml=0.2.5=h3422bc3_2
  - zlib=1.2.11=h90dfc92_1014
  - zstd=1.5.0=h8574219_0
  - pip:
    - appnope==0.1.2
    - asttokens==2.0.5
    - backcall==0.2.0
    - cachecontrol==0.12.10
    - cachy==0.3.0
    - charset-normalizer==2.0.12
    - cleo==0.8.1
    - click==8.1.2
    - clikit==0.6.2
    - crashtest==0.3.1
    - decorator==5.1.1
    - deprecation==2.1.0
    - executing==0.8.3
    - fonttools==4.31.2
    - html5lib==1.1
    - idna==3.3
    - importlib-metadata==4.11.3
    - intervaltree==3.1.0
    - ipython==8.2.0
    - jedi==0.18.1
    - jinja2==3.1.1
    - jsonpickle==2.1.0
    - keyring==23.5.0
    - kiwisolver==1.4.2
    - lockfile==0.12.2
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.3
    - mpmath==1.2.1
    - msgpack==1.0.3
    - numpy==1.22.3
    - packaging==20.9
    - pandas==1.4.1
    - parso==0.8.3
    - pastel==0.2.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.1
    - pip==22.0.4
    - pkginfo==1.8.2
    - pm4py==2.2.19.2
    - poetry==1.1.13
    - poetry-core==1.0.8
    - prompt-toolkit==3.0.28
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pydotplus==2.0.2
    - pygments==2.11.2
    - pylev==1.4.0
    - pytest==7.1.1
    - python-graphviz==0.19.1
    - pyvis==0.1.9
    - requests==2.27.1
    - requests-toolbelt==0.9.1
    - scipy==1.8.0
    - shellingham==1.4.0
    - simpy==4.0.1
    - sortedcontainers==2.4.0
    - stack-data==0.2.0
    - stringdist==1.0.9
    - sympy==1.10.1
    - tomli==2.0.1
    - tomlkit==0.10.1
    - traitlets==5.1.1
    - urllib3==1.26.9
    - virtualenv==20.14.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - zipp==3.8.0
prefix: /Users/ihar/.miniconda3/envs/simod
