version: 5
##########
# Common #
##########
common:
  # Path to the event log in CSV format
  train_log_path: ../../event_logs/BPIC_2012_W_train.csv.gz
  # Event log to evaluate the discovered BPS model with
  test_log_path: ../../event_logs/BPIC_2012_W_test.csv.gz
  # Specify the name for each of the columns in the CSV file (XES standard by default)
  log_ids:
    case: "case_id"
    activity: "activity"
    resource: "resource"
    start_time: "start_time"
    end_time: "end_time"
  # Number of evaluations of the discovered BPS model
  num_final_evaluations: 10
  # Metrics to evaluate the discovered BPS model
  evaluation_metrics:
    - 3_gram_distance
    - 2_gram_distance
    - absolute_event_distribution
    - relative_event_distribution
    - circadian_event_distribution
    - arrival_event_distribution
    - cycle_time_distribution
  # Whether to discover case attributes or not
  discover_data_attributes: false
#################
# Preprocessing #
#################
preprocessing:
  multitasking: false
  enable_time_concurrency_threshold: 0.5
################
# Control-flow #
################
control_flow:
  # Metric to guide the optimization process (loss function to minimize)
  optimization_metric: two_gram_distance
  # Number of optimization iterations over the search space
  num_iterations: 30
  # Number of times to evaluate each iteration (using the mean of all of them)
  num_evaluations_per_iteration: 5
  # Methods for discovering gateway probabilities
  gateway_probabilities: discovery
  # Discover process model with SplitMiner v3
  mining_algorithm: sm1
  # Number of concurrent relations between events to be captured
  epsilon:
    - 0.05
    - 0.4
  # Threshold for filtering the incoming and outgoing edges
  eta:
    - 0.2
    - 0.7
  # Whether to replace non-trivial OR joins or not
  replace_or_joins:
    - true
    - false
  # Whether to prioritize parallelism over loops or not
  prioritize_parallelism: true
##################
# Resource model #
##################
resource_model:
  # Metric to guide the optimization process (loss function to minimize)
  optimization_metric: circadian_emd
  # Number of optimization iterations over the search space
  num_iterations: 40
  # Number of times to evaluate each iteration (using the mean of all of them)
  num_evaluations_per_iteration: 5
  # Whether to discover prioritization or batching behavior
  discover_prioritization_rules: false
  discover_batching_rules: false
  # Resource profiles configuration
  resource_profiles:
    # Resource profile discovery type
    discovery_type: differentiated_fuzzy
    # Time granularity (in minutes) for the resource calendar (the higher the density of events in the log, the smaller the granularity can be)
    granularity: 60
    fuzzy_angle:
      - 0.1
      - 0.9
